### ISSUE TITLE
npm run test , error

### ISSUE THREAD

**Issue by qkren** [node-ffi-libraries/node-ffi-library-libusb-v1.0.23#2]
This is me again

when i run the command npm run test , the demo is Run failed on windows

  for ([header, headerLoader] of Object.entries(library.headers)) {
    console.log(headerLoader)
    headers[header] = await headerLoader(); // This step reports an error
  }
Some people say extern "C"， when it's exported
UnhandledPromiseRejectionWarning: Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (D:\test\node-ffi-library-libusb-v1.0.23-develop\node_modules\ffi-napi\lib\dynamic_library.js:113:11)
    at D:\test\node-ffi-library-libusb-v1.0.23-develop\node_modules\ffi-napi\lib\library.js:55:21
    at Array.forEach (<anonymous>)
    at new Library (D:\test\node-ffi-library-libusb-v1.0.23-develop\node_modules\ffi-napi\lib\library.js:52:28)
    at Object.<anonymous> (D:\test\node-ffi-library-libusb-v1.0.23-develop\platforms\windows-x86_64\include\libusb-1.0\libusb.h.js:116:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:21540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by qkren** [comment]
it worked on macOS but not windows,

**Comment by joelpurra** [comment]
@qkren: I know you said you are running `windows-x86_64`, but are you perhaps mixing it with 32 bit versions of some software, like the compiler? I see `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` in your file paths in https://github.com/node-ffi-libraries/node-ffi-library-libusb-v1.0.23/issues/1#issuecomment-834086371.

"Win32 error 127" is `ERROR_PROC_NOT_FOUND`, which seems to hint at 32/64 bit problems.

- https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

**Comment by joelpurra** [comment]
@qkren: just updated this library to v2.0.0, with upgrade `ffi-napi`/`ref-napi` dependencies etcetera. Does it work better?

Btw, all code is fully generated by https://github.com/node-ffi-packager/node-ffi-packager v2.0.0 (that is where the version number comes from).
